In [3]:
import numpy as np

In [30]:
a = np.random.random((3,3))

b = np.random.random((3,1))

# print(a)

print(a[0,:])
print(b[:,0])


sum = 0
for x, y in zip(a[0,:], b[:,0]):
    # print( x * y)
    print ( x * y )
    sum += x * y
print(sum)

np.dot(a, b)

[0.99418479 0.52639739 0.54737383]
[0.49145897 0.64064141 0.41850929]
0.4886010361832088
0.33723196541317807
0.22908103440740685
1.0549140360037936


array([[1.05491404],
       [0.96642359],
       [1.16506167]])

In [ ]:
a = np.arange(-5,5)

(a > 0).astype(error_tensor.dtypeint)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [1]:
from Layers.ReLU import ReLU

relu = ReLU()
print(relu)


In [38]:
import numpy as np
from Optimization import Loss

a = np.array([[1,0,0], [0,1,0]])
a = np.clip(a, 1e-12, 1.0 - 1e-12)

from Optimization import Loss
cr = Loss.CrossEntropyLoss()
print(cr.forward(a, a))

1.1252404022027295e-10


In [62]:
a = np.random.rand(3,3)

b = np.max(a, axis=1, keepdims=True)


exp = np.exp(a-b)
sum_exp = np.sum(exp, axis=1, keepdims=True)
pred =exp / sum_exp 
print(pred)

[[0.23357165 0.29718911 0.46923924]
 [0.39339784 0.27062234 0.33597982]
 [0.20164957 0.4032543  0.39509613]]


In [65]:
label = np.array([
    [1, 0, 0],  # sample 1 → class 0
    [0, 1, 0],  # sample 2 → class 1
    [0, 0, 1]   # sample 3 → class 2
])

pred[0][0] = 1

-label * np.log(pred)

array([[-0.        , -0.        , -0.        ],
       [-0.        ,  1.30703101, -0.        ],
       [-0.        , -0.        ,  0.92862617]])

In [74]:
import numpy as np

# random prediction matrix
a = np.random.rand(9, 4)

# stable softmax
b = np.max(a, axis=1, keepdims=True)
exp = np.exp(a - b)
sum_exp = np.sum(exp, axis=1, keepdims=True)
pred = exp / sum_exp

print("Original softmax prediction:")
print(pred)

# Label tensor (one-hot)
label = np.array([
    [1, 0, 0],   # sample 1 → class 0
    [0, 1, 0],   # sample 2 → class 1
    [0, 0, 1]    # sample 3 → class 2
])

label = np.zeros([9, 4])
for i in range(9):
    label[i, np.random.randint(0, 4)] = 1

print(label)
print()
# Cross-entropy term -y * log(y_hat)
ce_matrix = -label * np.log(pred)    # stability (same as your tests)

print("\nCross-entropy result (element-wise):")
print(ce_matrix)

loss = np.sum(ce_matrix)
print("\nTotal Loss =", loss)


Original softmax prediction:
[[0.28188344 0.22521579 0.19752971 0.29537107]
 [0.22061411 0.39674304 0.19574306 0.18689979]
 [0.24022556 0.24305049 0.1463345  0.37038946]
 [0.15820561 0.2760891  0.21909182 0.34661347]
 [0.12329175 0.2737069  0.31191427 0.29108709]
 [0.16439043 0.27880138 0.25063562 0.30617257]
 [0.32101742 0.32134521 0.14818323 0.20945414]
 [0.26621765 0.26792908 0.26327419 0.20257908]
 [0.17373739 0.30391441 0.19506105 0.32728716]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Cross-entropy result (element-wise):
[[1.26626164 0.         0.         0.        ]
 [0.         0.92446647 0.         0.        ]
 [1.42617698 0.         0.         0.        ]
 [0.         0.         0.         1.05954504]
 [2.09320181 0.         0.         0.        ]
 [1.80551104 0.         0.         0.        ]
 [0.         1.13523931 0.         0.        ]
 [0.         0.         1.33455925 0.      

In [4]:
import numpy as np

batch_size = 9   # match what the original test expects
categories = 4

# one-hot labels
label_tensor = np.zeros((batch_size, categories))
label_tensor[:, 2] = 1  # correct class is 2

# input logits
input_tensor = np.zeros_like(label_tensor)
input_tensor[:, 1] = 1  # model predicts class 1 strongly

# CrossEntropyLoss (logits version)
def cross_entropy_with_logits(logits, labels):
    shifted = logits - np.max(logits, axis=1, keepdims=True)
    log_sum_exp = np.log(np.sum(np.exp(shifted), axis=1, keepdims=True))
    log_softmax = shifted - log_sum_exp
    loss = -np.sum(labels * log_softmax)
    return loss, np.exp(log_softmax)

loss, softmax_pred = cross_entropy_with_logits(input_tensor, label_tensor)

print("Softmax prediction (first sample):", softmax_pred[0])
print("Loss:", loss)


Softmax prediction (first sample): [0.1748777  0.47536689 0.1748777  0.1748777 ]
Loss: 15.693015425658114
