In [1]:
import numpy as np

In [30]:
a = np.random.random((3,3))

b = np.random.random((3,1))

# print(a)

print(a[0,:])
print(b[:,0])


sum = 0
for x, y in zip(a[0,:], b[:,0]):
    # print( x * y)
    print ( x * y )
    sum += x * y
print(sum)

np.dot(a, b)

[0.99418479 0.52639739 0.54737383]
[0.49145897 0.64064141 0.41850929]
0.4886010361832088
0.33723196541317807
0.22908103440740685
1.0549140360037936


array([[1.05491404],
       [0.96642359],
       [1.16506167]])

In [ ]:
a = np.arange(-5,5)

(a > 0).astype(error_tensor.dtypeint)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [13]:
from Layers.ReLU import ReLU

relu = ReLU()
print(relu)


ModuleNotFoundError: No module named 'Layers'

In [15]:
a = np.random.rand(3,3)

from Optimization import Loss
cr = Loss.CrossEntropyLoss()

print(cr.forward(a, a))

ImportError: cannot import name 'Loss' from 'Optimization' (/home/eren/Desktop/Deep Learning/Exercises/2/ex1/playGround/Optimization/__init__.py)